StartupEvents.registry('item', (event) => {
	event.create('sacred_salt')
    .displayName('Alchemical Salt [§cSacred§r]')
    .tag('theurgy:alchemical_salts')
	event.create('wicked_salt')
    .displayName('Alchemical Salt [§1Wicked§r]')
    .tag('theurgy:alchemical_salts')
	event.create('arcane_salt')
    .displayName('Alchemical Salt [§dArcane§r]')
    .tag('theurgy:alchemical_salts')
	event.create('eldritch_salt')
    .displayName('Alchemical Salt [§5Eldritch§r]')
    .tag('theurgy:alchemical_salts')
	event.create('aerial_salt')
    .displayName('Alchemical Salt [§bAerial§r]')
    .tag('theurgy:alchemical_salts')
	event.create('aqueous_salt')
    .displayName('Alchemical Salt [§9Aqueous§r]')
    .tag('theurgy:alchemical_salts')
	event.create('earthen_salt')
    .displayName('Alchemical Salt [§aEarthen§r]')
    .tag('theurgy:alchemical_salts')
	event.create('infernal_salt')
    .displayName('Alchemical Salt [§6Infernal§r]')
    .tag('theurgy:alchemical_salts')
	event.create('umbral_salt')
    .displayName('Alchemical Salt [§8Umbral§r]')
    .tag('theurgy:alchemical_salts')

	event.create('infernal_niter', 'theurgy:alchemical_niter')
		.niterIcon('wizards_reborn:fire_crystal')
		.sourceName("Infernal Will")
		.sulfurTier("common")
	event.create('aqueous_niter', 'theurgy:alchemical_niter')
		.niterIcon('wizards_reborn:water_crystal')
		.sourceName("Aqueous Will")
		.sulfurTier("common")
	event.create('earthen_niter', 'theurgy:alchemical_niter')
		.niterIcon('wizards_reborn:earth_crystal')
		.sourceName("Earthen Will")
		.sulfurTier("common")
	event.create('aerial_niter', 'theurgy:alchemical_niter')
		.niterIcon('wizards_reborn:air_crystal')
		.sourceName("Aerial Will")
		.sulfurTier("common")
	event.create('nullified_niter', 'theurgy:alchemical_niter')
		.niterIcon('wizards_reborn:void_crystal')
		.sourceName("Nullified Will")
		.sulfurTier("common")

	event.create('demonic_niter', 'theurgy:alchemical_niter')
		.niterIcon('bloodmagic:defaultcrystal')
		.sourceName("Demonic Will")
		.sulfurTier("rare")
	event.create('corrosive_niter', 'theurgy:alchemical_niter')
		.niterIcon('bloodmagic:corrosivecrystal')
		.sourceName("Corrosive Will")
		.sulfurTier("rare")
	event.create('vengeful_niter', 'theurgy:alchemical_niter')
		.niterIcon('bloodmagic:vengefulcrystal')
		.sourceName("Vengeful Will")
		.sulfurTier("rare")
	event.create('destructive_niter', 'theurgy:alchemical_niter')
		.niterIcon('bloodmagic:destructivecrystal')
		.sourceName("Destructive Will")
		.sulfurTier("rare")
	event.create('steadfast_niter', 'theurgy:alchemical_niter')
		.niterIcon('bloodmagic:steadfastcrystal')
		.sourceName("Steadfast Will")
		.sulfurTier("rare")
})