
#Settings for tool parameters
[tool]
	#How quickly do the Moonsnare jars generate ember? Set to -1 to disable. [default: 3]
	#Range: -1 ~ 40
	moonsnare_strength = 3
	#How strong is the self-repair effect of aetherium tools? Set to -1 to disable. [default: 3]
	#Range: -1 ~ 40
	aetheric_strength = 3
	#How strong should each tick of Moongaze damage be? [default: 4.0]
	#Range: 0.0 ~ 20.0
	moongaze_strength = 4.0
	#List of dimensions that are always considered moonlit for Moonsnare containers and Aetheriuc tools.
	aetheric_dimensions = ["minecraft:the_end"]
	#Ember used when using the AOE mode on aetheric tools. [default: 4.0]
	ember_use = 4.0
	#Syntax is ( block|block|...|block ). List of sets of blocks that are considered identical for certain aetherium tool effects.
	same_blocks = ["minecraft:oak_log|minecraft:oak_wood", "minecraft:birch_log|minecraft:birch_wood", "minecraft:spruce_log|minecraft:spruce_wood", "minecraft:jungle_log|minecraft:jungle_wood", "minecraft:dark_oak_log|minecraft:dark_oak_wood", "minecraft:acacia_log|minecraft:acacia_wood", "minecraft:mangrove_log|minecraft:mangrove_wood", "minecraft:cherry_log|minecraft:cherry_wood", "minecraft:crimson_stem|minecraft:crimson_hyphae", "minecraft:warped_stem|minecraft:warped_hyphae", "minecraft:azalea_leaves|minecraft:flowering_azalea_leaves"]

	[tool.pobs]
		#Maximum vein mine radius of the Pickaxe of the Boundless Sky. [default: 8]
		#Range: 0 ~ 128
		range = 8

	[tool.pomd]
		#Maximum number of boreholes the Pickaxe of the Molten Depths makes when tunneling. [default: 8]
		#Range: 0 ~ 128
		range = 8

	[tool.aotr]
		#Maximum recursions the Axe of the Twisted Realm can do while chopping. [default: 512]
		#Range: 0 ~ 2048
		range = 512

	[tool.aosa]
		#Maximum growing radius of the Axe of the Sonorous Archives. [default: 24]
		#Range: 0 ~ 128
		range = 24

	[tool.soic]
		#Maximum replacement radius of the Shovel of the Ineluctable Changes. [default: 16]
		#Range: 0 ~ 128
		range = 16

	[tool.sotc]
		#Fluid capacity of the Shovel of the Timeless Cascades. [default: 4096]
		#Range: 0 ~ 1048576
		capacity = 4096

	[tool.hovh]
		#Maximum row length that can be tilled by the Hoe of the Villatic Harvest. [default: 32]
		#Range: 1 ~ 64
		till_range = 32
		#Maximum harvest radius of the Hoe of the Villatic Harvest. [default: 12]
		#Range: 1 ~ 64
		harvest_range = 12

	[tool.crossbow]
		#Ember cost of loading an aetherium crossbow. [default 10]
		ember_use = 10.0

		[tool.crossbow.magma]
			#How many entities the Crossbow of the Shattered Reflection is allowed to chain to. [default 16]
			chain_limit = 16
			#How far can an entity be for the Crossbow of the Shattered Reflection to chain to them. [default 16.0]
			chain_range = 16.0

	[tool.crown]
		#Cube radius of the area of effect the Aetherium Crown applies to. [default: 8.0]
		radius = 8.0
		#Syntax is ( original|replacement ). Effects that should be replaced with another when put into a Vessel Gem.
		potion_banned = ["minecraft:instant_health|minecraft:regeneration", "minecraft:instant_damage|minecraft:wither"]

	[tool.tuning_cylinder]
		#Base chance (1/X) per level to drop a geode when using the Tuning Cylinder augment. [default: 32]
		chance = 32

		[tool.tuning_cylinder.deep]
			#At what depth should deep geodes start dropping?
			depth = 0
			#What dimensions should be able to drop this geode?
			dimensions = ["minecraft:overworld"]

#Settings for block parameters
[block]

	[block.forge]

		[block.forge.tool_station]
			#Number of hits required to work a tool in the Forge Tool Station. [default: 30]
			hits = 30

